### PR TITLE
Trying to allow invalid syntax as "bad character" instead of crashing…

### PR DESCRIPTION
**Pull request by ice1000**
… the editor

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Thanks again!

**Comment by ice1000** [comment]
I've reproduced the issue introduced in #387 and now I can't reproduce.

**Comment by rikvdkleij** [comment]
Hmm, but `OPTIONS_GHC` is not used in bnf?

**Comment by ice1000** [comment]
Yes. Is that something important? Now you can put anything seem-to-valid in the pragma (like an identifier `OPTIONS_GHC`, option `--OhMyGod`, or a string/char lit `" Spaces Around "`).

**Comment by ice1000** [comment]
> Hmm, but `OPTIONS_GHC` is not used in bnf?

I've just realized that this is not only an old tokentype but a lexer state. I don't think it has something to do with the bnf.

**Comment by rikvdkleij** [comment]
> Yes. Is that something important? Now you can put anything seem-to-valid in the pragma (like an identifier `OPTIONS_GHC`, option `--OhMyGod`, or a string/char lit `" Spaces Around "`).

No, I just learned something :smile: 
Normally I have to set it in the bnf otherwise the compiler complains.

I can confirm that is now works! Great!

Only the syntax highlighter does not highlight `LANGUAGE` anymore. 

I will fix other features like intention to add language pragma.

**Comment by ice1000** [comment]
@rikvdkleij we're getting this parser for free.


I'm cleaning up the bnf and will PR again very soon.

**Comment by rikvdkleij** [comment]
@ice1000  Super!

**Pull request merged**
