### PR TITLE
Add live template contexts and some default live templates

### PR DESCRIPTION
**Pull request by ice1000**
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2612207/intellij-haskell.zip)

Will attach screenshots soon

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Thanks! Also for the ping.

**Comment by ice1000** [comment]
@rikvdkleij Please take a look at #330

**Comment by ice1000** [comment]
@rikvdkleij Please take a look.

**Comment by rikvdkleij** [comment]
Thanks again!

**Comment by ice1000** [comment]
@rikvdkleij I'm still not quite satisfied with the global declaration context.
However, the pragma context is working like a charm:

a

I'm gonna improve the global declaration soon.

**Comment by rikvdkleij** [comment]
It's a cool feature!

**Comment by ice1000** [comment]
Yeah, you can see that completion for `language` doesn't popup after `module` but does around other pragmas.
I want to do the same thing for global declarations and I'm having a little problems with it.

**Pull request merged**
