### PR TITLE
Update pragma/function name highlight and color settings page, move config page

### LINKED ISSUE #332: Ignore keywords in regular pragmas
Repro: 

* Consider following source fragment:
  ```haskell
  {-# OPTIONS_GHC -fno-warn-type-defaults #-}
  ```

Expected: `type` is not highlighted as keyword

Instead: 
image

### PR DESCRIPTION
**Pull request by ice1000**
Fixes #332

### CODE REVIEW

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2625648/intellij-haskell.zip)

**Comment by ice1000** [comment]
Maybe a special highlighting for pragma should be added.

**Comment by develop7** [comment]
> Maybe a special highlighting for pragma should be added.

Makes sense, since there's whole lot of these pragmas where keywords highlighting would be useful, e.g. `REWRITE`, `SPECIALIZE` or `MINIMAL`.

**Comment by ice1000** [comment]
image

Well it's not very well done, I may need to override the font style (bold to regular) as well.

**Comment by ice1000** [comment]
A problem is, my Windows laptop has stack installed so it works well with intellij-haskell but there's no JDK and Scala SDK on it, while my Linux laptop has only cabal so it doesn't work with intellij-haskell but there's full JVM/IntelliJ plugin dev environment on it.
My process of contributing to this repo is, use my Linux laptop to modify the code, submit PR, build a zip, upload on GitHub, download and test on my Windows laptop and show screenshots to you guys...

This is very painful..

**Comment by rikvdkleij** [comment]
@ice1000 Sorry to hear it's painful. Why don't you install stack on your linux laptop?

**Comment by develop7** [comment]
Second that, should definitely do the job.

**Comment by ice1000** [comment]
> @ice1000 Sorry to hear it's painful. Why don't you install stack on your linux laptop?

It's too large 😂 

Well, I'm fine with it anyway. Me myself is a plugin developer -- I'm the owner of the Julia plugin.

**Comment by ice1000** [comment]
@rikvdkleij What do u think of #333 ? What's actually painful is maintaining two PRs at the same time.

**Comment by rikvdkleij** [comment]
> What's actually painful is maintaining two PRs at the same time.

That is easily solved 😄  Thanks!

**Comment by rikvdkleij** [comment]
> Well, I'm fine with it anyway. Me myself is a plugin developer -- I'm the owner of the Julia plugin.

It's really great that you are using your experience to improve this plugin!

**Comment by ice1000** [comment]
> It's really great that you are using your experience to improve this plugin!

Yeah, we're all plugin developers. So we share the same goal, the same pain :joy:

**Comment by ice1000** [comment]
Rebased! Maybe we need to provide default color settings.

**Comment by ice1000** [comment]
Don't merge right now, I may want to add more syntax highlight.

**Comment by rikvdkleij** [comment]
Ok, let me know when it's finished.

**Comment by ice1000** [comment]
I want to move Haskell's settings to the `Languae & Framework` section

**Comment by develop7** [comment]
Makes perfect sense to me

**Comment by rikvdkleij** [comment]
> I want to move Haskell's settings to the Languae & Framework section

Good idea.

**Comment by ice1000** [comment]
image
I'm really really really sorry to bring this. I'm gonna fix it

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2625959/intellij-haskell.zip)

**Comment by ice1000** [comment]
image

Hand-written Swing! It's aweful!
image

IntelliJ UI-Designer! It's nice!

**Comment by develop7** [comment]
> U forget hoogle!

Could we not spellcheck stuff coming from external libraries instead?

**Comment by ice1000** [comment]
> Could we not spellcheck stuff coming from external libraries instead?

This is hard to implement, the API is inconvenient for doing this.

**Comment by develop7** [comment]
> This is hard to implement, the API is inconvenient for doing this.

Should we ask JetBrains to implement this instead?

**Comment by ice1000** [comment]
> Should we ask JetBrains to implement this globally instead?

I don't think so. It's hard to explain why if you have no idea about the IntelliJ-Platform architecture.

**Comment by ice1000** [comment]
There's a chat room for plugin developers: https://gitter.im/IntelliJ-Plugin-Developers/Lobby

**Comment by ice1000** [comment]
Wow!
image
image

**Comment by ice1000** [comment]
Oh! My essay! 😨

**Comment by ice1000** [comment]
Well, I'm not happy with this icon.
image

Maybe should keep the original haskell.png

**Comment by ice1000** [comment]
image

Beautiful!

**Comment by ice1000** [comment]
Ping @rikvdkleij

**Comment by rikvdkleij** [comment]
Thanks!!

**Pull request merged**
