### PR TITLE
[ fix #335 ] Support Alex files

### LINKED ISSUE #335: Support Alex ".x" files
Just like how Grammar-Kit plugin support ".flex" files.

### PR DESCRIPTION
**Pull request by ice1000**
Related discussion and screenshots are in #335.

### CODE REVIEW

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2636635/intellij-haskell.zip)

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2636643/intellij-haskell.zip)

Icons updated

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2636775/intellij-haskell.zip)

Trying to support reference resolving but it seems not working well.

**Comment by ice1000** [comment]
Now we have completions for token sets. Yay!

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2636812/intellij-haskell.zip)

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2636828/intellij-haskell.zip)
Bug fixes.
I was so stupid..

**Comment by ice1000** [comment]
a

Very nice!

**Comment by rikvdkleij** [comment]
Thanks 👍

**Pull request merged**
