### PR TITLE
Fix add paren intention for one character expression

### PR DESCRIPTION
**Pull request by zjhmale**
Fix issue mentioned at #59

screenshot

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Thanks!

**Comment by rikvdkleij** [comment]
@zjhmale It does not work if expression contains `.` an call paren intention action if cursor is on `.`

**Comment by zjhmale** [comment]
Ok, I'll fix that!

**Comment by zjhmale** [comment]
Hi Rik, I can not reproduce the issue on my side, can you give me some corner case code snippets to reproduce it?

sceenshot

>@zjhmale It does not work if expression contains . an call paren intention action if cursor is on .

**Comment by zjhmale** [comment]
And you mean even the `add paren` intention action does not work?
>@zjhmale It does not work if expression contains . an call paren intention action if cursor is on .

**Comment by rikvdkleij** [comment]
As your animated gif but without selecting the expression.

**Comment by zjhmale** [comment]
Ok, I got it.

**Comment by rikvdkleij** [comment]
Similar problem with for example `x:xs`

**Comment by zjhmale** [comment]
Hi Rik, if the expected behavior is

`foo.bar` <=> `(foo.bar)`

`foo:bar` <=> `(foo:bar)`

when the cursor is on `.` and `:`.

I think it is quite impossible to implement at this moment because `foo.bar` is not the parent element of `.bar`. So the safest way to use these two intention actions is to apply them when we select the expression we want to apply to 😄

**Comment by rikvdkleij** [comment]
Yes, that is expected behavior.

You can try to use nextSibling and/or prevSibling. 

But selecting is the expression is okay :smile:

**Pull request merged**
