### PR TITLE
turn on hlint inspection by default

### LINKED ISSUE #37: Does hlint work?
Inspection by HLint;
Quick fixes for HLint suggestions;

How does it work? I don't see any suggestions.

### PR DESCRIPTION
**Pull request by zjhmale**
Fix #37 

@rikvdkleij 

and btw, maybe we should refactor https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/inspection/HlintQuickfix.scala to get a better quick fix functionality.

for now it just doesn't work out sometimes.

report

### CODE REVIEW

**Comment by yury-pachin** [comment]
And it will be more useful with show what exactly found and suggest in popup.

**Comment by zjhmale** [comment]
i'm working on this.
>And it will be more useful with show what exactly found and suggest in popup.

**Comment by rikvdkleij** [comment]
Also replacing current code by the HLint suggested code is complex and needs a lot of testing with different scenarios.

**Comment by zjhmale** [comment]
seems `ProblemDescriptorBase` does not support multiline? @rikvdkleij 

you mean what different scenarios?
>Also replacing current code by the HLint suggested code is complex and needs a lot of testing with different scenarios.

**Comment by rikvdkleij** [comment]
I mean PSI tree of original code can be different than PSI tree of suggested code, as with code over multiple lines.

**Comment by rikvdkleij** [comment]
Btw, how do you create those nice tiny screenshots?

**Comment by zjhmale** [comment]
http://www.cockos.com/licecap/ a little screen capture tool here 😄 
>Btw, how do you create those nice tiny screenshots?

**Comment by zjhmale** [comment]
can you show a test case here? i can not imagine the issue 😂 
>I mean PSI tree of original code can be different than PSI tree of suggested code, as with code over multiple lines.

**Comment by rikvdkleij** [comment]
A solution could be to integrate `hindent` in plugin, so suggested code gets formatted well

**Comment by zjhmale** [comment]
good point 👍  i will take a look at that later.
>A solution could be to integrate hindent in plugin, so suggested code gets formatted well

**Comment by zjhmale** [comment]
ready to be merged @rikvdkleij , will improve quickfix use `hindent` next pr.

**Comment by zjhmale** [comment]
poke @rikvdkleij

**Comment by rikvdkleij** [comment]
@zjhmale 
Hmm, if hlint suggests to remove something the suggestion text is not proper. 

Did you see code in HlintQuickfix#getText ?

**Comment by zjhmale** [comment]
Why not proper? the suggestion text just show what hlint inspect.
>Hmm, if hlint suggests to remove something the suggestion text is not proper.

nope , i will check this out tomorrow, so tired today 😂 
>Did you see code in HlintQuickfix#getText ?

**Comment by rikvdkleij** [comment]
I mean, `to`can be empty. So in that case you display something as `Found [...] why not:`

**Comment by zjhmale** [comment]
got it, i will fix that.
>I mean, tocan be empty. So in that case you display something as Found [...] why not:

**Comment by rikvdkleij** [comment]
hlint is optional dependency so not by default enabled.

**Comment by andrewufrank** [comment]
where can i switch off hlint? i did not see it mentioned anywhere in a setting.

by the way: hlint is not a perfect check for haskell code. it does not check the cabal file and thus complains for imports which occur with the same name in two packages (e.g. control monad which is in mtl and monads-tf). needs an annoying PackageImport clause.

**Pull request closed without merging**
