### PR TITLE
Support string literal language injection

### LINKED ISSUE #272: Multiline strings aren't highlighted
If you use`\` to create a multiline string, it's not highlighted like a regular string.

If you copy and paste the string, it's highlighted correctly.

Example: 
screen shot 2018-05-02 at 11 18 28 am

### PR DESCRIPTION
**Pull request by ice1000**
And fix #272 by the way.

### CODE REVIEW

**Comment by ice1000** [comment]
[intellij-haskell.zip](https://github.com/rikvdkleij/intellij-haskell/files/2678253/intellij-haskell.zip)

**Comment by ice1000** [comment]
DO NOT MERGE.
Some local changes cannot be pushed due to my PC's internet connection problem.
Please wait patiently.

**Comment by ice1000** [comment]
Writing down some notes:

https://github.com/covscript/covscript-intellij/blob/master/src/org/covscript/lang/psi/cov-manipulators.kt
https://github.com/covscript/covscript-intellij/blob/master/src/org/covscript/lang/psi/impl/cov-psi-mixins.kt

**Comment by rikvdkleij** [comment]
Thanks!

**Comment by rikvdkleij** [comment]
@ice1000 I see that #272 is fixed but what else gives this change as feature to the user?

**Comment by ice1000** [comment]
screen

Do you like what you see?

**Comment by ice1000** [comment]
I've just found a bug. Will fix tonight

**Comment by ice1000** [comment]
> Does it also work for SQL

Yes

> with code completion of table and field names

No :(

**Comment by rikvdkleij** [comment]
It looks like this change broke the feature that inserts automatically closing `"` after entering starting `"`.

**Comment by ice1000** [comment]
How?
Is there some old codes about that feature? I may take a look.

**Comment by rikvdkleij** [comment]
The implementation is minimal, see `HaskellQuoteHandler`. I already added `HS_TEXT_LITERAL` but that does not help.

**Comment by rikvdkleij** [comment]
Btw, I checked out revision before this change and there it still works.

**Comment by ice1000** [comment]
Writing down some notes:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/205418330-Quote-handler-in-template-language
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206115129-Inserting-Closing-Quote-and-Bracket

**Comment by rikvdkleij** [comment]
> You can see that it only accepts tokens, not Psi element types

You mean that the String Literal Injection feature changed the "behavior" of `"` so it's not a token anymore at that location?

**Comment by ice1000** [comment]
No, I still don't know why is that happening. 😅

**Pull request merged**
