### PR TITLE
Trying to fix #339

### LINKED ISSUE #339: Internal error when create module
a

### PR DESCRIPTION
**Pull request by ice1000**
DO NOT MERGE RIGHT NOW.
For testing and discussion.

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Works on mac and linux. 

Thanks!

**Comment by ice1000** [comment]
However, the created module has an absurd name.
I'll consider fixing it later

**Comment by rikvdkleij** [comment]
Hmm, I have tested that..

**Comment by ice1000** [comment]
See the image posted in #339

**Comment by ice1000** [comment]
The created module name becomes the absolute path.
It's weird.

BTW, stack REPL seem not to import the dependencies.
I got some errors on `import`s of dependencies

**Pull request merged**
