### PR TITLE
Support Cabal File

### PR DESCRIPTION
**Pull request by zjhmale**
The mature Cabal file parser is ported and adjusted from another great work [intellij-haskforce](https://github.com/carymrobbins/intellij-haskforce/tree/master/src/com/haskforce/cabal).

We all use `apache-2.0`, and there are no notices on the original parser files.

* Syntax highlighting and color setting page for Cabal file.
* Auto-completion for Haskell module.
* Haskell module navigation.

screenshot

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Cool! Thanks!

**Comment by rikvdkleij** [comment]
@zjhmale Can you check the compiler warnings in `CabalParser.scala`?

**Comment by zjhmale** [comment]
@rikvdkleij Yes, I'll try to omit those annoying warnings.

**Comment by rikvdkleij** [comment]
@zjhmale I get NPE in `ModulePartImpl`:
ava.lang.NullPointerException
	at intellij.haskell.cabal.lang.psi.impl.ModulePartImpl.resolveToModuleDir(ModulePartImpl.scala:66)
	at intellij.haskell.cabal.lang.psi.impl.ModulePartImpl.resolve(ModulePartImpl.scala:54)
	at intellij.haskell.cabal.lang.psi.impl.ModulePartImpl.resolve$(ModulePartImpl.scala:52)
	at intellij.haskell.cabal.lang.psi.ModulePart.resolve(CabalCompositeElement.scala:26)
	at intellij.haskell.cabal.lang.psi.CabalReference.resolve(CabalReference.scala:13)
	at com.intellij.psi.PsiReferenceBase.isReferenceTo(PsiReferenceBase.java:125)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:52)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$8.lambda$execute$0(PsiSearchHelperImpl.java:734)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:138)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:224)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$8.execute(PsiSearchHelperImpl.java:730)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:232)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:228)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:32)
	at com.intellij.openapi.application.ReadActionProcessor$1.compute(ReadActionProcessor.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:895)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:29)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processVirtualFile$4(PsiSearchHelperImpl.java:376)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:46)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:360)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processPsiFileRoots$2(PsiSearchHelperImpl.java:313)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by zjhmale** [comment]
@rikvdkleij I'll address this.

**Comment by rikvdkleij** [comment]
While navigating but you can  solve by just to looking the code

**Comment by rikvdkleij** [comment]
resolve() and resolveToModuleDir() are mutally recursive and the latter can return null. Also resolveToModuleDecl() can return null.

**Comment by rikvdkleij** [comment]
@zjhmale I get this warning when I run JFlex generator for `_CabalParsingLexer.flex`:
`Warning in file "_CabalParsingLexer.flex" (line 51): 
Expression matches the empty string, which may lead to non-termination.
  {CRLF}*  { return CabalTypes.WHITE_SPACE; }`

**Comment by zjhmale** [comment]
Copy, I will fix that :)
>@zjhmale I get this warning when I run JFlex generator for _CabalParsingLexer.flex:
Warning in file "_CabalParsingLexer.flex" (line 51): Expression matches the empty string, which may lead to non-termination. {CRLF}* { return CabalTypes.WHITE_SPACE; }

**Pull request merged**
