### PR TITLE
Implement new parser, close #382, close #332

### LINKED ISSUE #332: Ignore keywords in regular pragmas
Repro: 

* Consider following source fragment:
  ```haskell
  {-# OPTIONS_GHC -fno-warn-type-defaults #-}
  ```

Expected: `type` is not highlighted as keyword

Instead: 
image

### LINKED ISSUE #382: optF pragma incorrectly parsed
Based on [tasty-discover documentation](https://hackage.haskell.org/package/tasty-discover) and [GHC spec](https://downloads.haskell.org/~ghc/8.6.3/docs/html/users_guide/phases.html?highlight=optf#ghc-flag--optF%20%E2%9F%A8option%E2%9F%A9), the string following `-optF` should be passed to the preprocessor.

Intellij Haskell incorrectly interprets options containing `--` in a pragma, example:
```haskell
{-# OPTIONS_GHC -F -pgmF tasty-discover -optF --tree-display #-}
```
The error is
```
Error:(1, 4) HaskellTokenType.CON_ID, HaskellTokenType.DIRECTIVE or HaskellTokenType.NEWLINE expected, got 'OPTIONS_GHC'
```

image

### PR DESCRIPTION
**Pull request by ice1000**
No, description, provided.

But please do add more tests to ensure that originally-accepted Haskell pragmas are still accepted in this new version.

### CODE REVIEW

**Comment by ice1000** [comment]
Also please check that if it breaks any completion/linting features. The AST is changed.

**Comment by rikvdkleij** [comment]
@ice1000 

Many thanks! Your help is great!

> But please do add more tests to ensure that originally-accepted Haskell pragmas are still accepted in this new version.

I will do my best :smile: 

> Also please check that if it breaks any completion/linting features. The AST is changed.

Will so some more testing.

**Comment by rikvdkleij** [comment]
@ice1000 
Hmm, somethings goes wrong.

When I try to enter a pragma the syntax highlighting for the whole file does weird and I can not remove tokens in the pragma.

Can you take a look?

**Comment by ice1000** [comment]
Sounds like some real tests are needed apart from test cases.
I'll check it right now.

**Comment by rikvdkleij** [comment]
Thanks!

> Sounds like some real tests are needed apart from test cases.

It looks your change broke some features but I have no problem with fixing that if parser and bnf are correctly working.

Also the handler which automatically enters the closing pragma is broken. I think because the pragma is now defined in the parser.
I think you forgot something because in the flex file still OPTIONS_GHC is defined while it's now in general for pragma's.

**Comment by ice1000** [comment]
I've digged a little and it sounds like it's more rubost

**Comment by rikvdkleij** [comment]
@ice1000 

FYI, this change broke automatically closing double quotes, fixed in https://github.com/rikvdkleij/intellij-haskell/commit/65ee5274d3742bedf93d3e6aab7ded12e2b367d8

**Comment by ice1000** [comment]
Again?
Oh no..

**Comment by ice1000** [comment]
Ah. I thought it's an unused lex fule. I'm sorry

**Comment by rikvdkleij** [comment]
@ice1000 

No problem :smile: Just FYI.

**Pull request merged**
