### PR TITLE
Address comments, support `do` notation

### PR DESCRIPTION
**Pull request by ice1000**
See the added test.

Note: I'm struggling with the generated code. I guessed you're running "code cleanup" before committing them, so did I. However, some of them are 2-spaces-indented, some are 4-spaces. I'm lost -- I regenerate the code and got most of them changed.
@rikvdkleij there should be a solution.

### CODE REVIEW

**Comment by ice1000** [comment]
I'll recommend setting a standard, like using `.editorconfig`.

**Comment by rikvdkleij** [comment]
> I'll recommend setting a standard, like using .editorconfig.

I would suggest to leave the code as is generated. If that is possible with `.editorconfig` then that is fine.

**Comment by rikvdkleij** [comment]
> I'm lost -- I regenerate the code and got most of them changed.
@rikvdkleij there should be a solution.

That is because I always format and optimize imports when I commit. But, yes, that is not a good practice for the generated code.

**Comment by rikvdkleij** [comment]
Thanks again!

**Comment by ice1000** [comment]
> I would suggest to leave the code as is generated. If that is possible with .editorconfig then that is fine.

The generated code's format depends on your IDE settings -- the plugin at least reads your code style configuration.
With `.editorconfig`, the code style will be enforced to the specified one.

**Pull request merged**
