### PR TITLE
Fix about page

### PR DESCRIPTION
**Pull request by zjhmale**
* Originally if I click the `About Haskell Project` button, it will introduce an NPE:

>null
java.lang.IllegalMonitorStateException
	at java.lang.Object.notify(Native Method)
	at intellij.haskell.HaskellNotificationGroup$.log(HaskellNotificationGroup.scala:104)
	at intellij.haskell.HaskellNotificationGroup$.balloonEvent(HaskellNotificationGroup.scala:98)
	at intellij.haskell.HaskellNotificationGroup$.logErrorBalloonEvent(HaskellNotificationGroup.scala:70)
	at intellij.haskell.settings.HaskellSettingsState$.notifyIfPathIsNotSet(HaskellSettingsState.scala:38)
	at intellij.haskell.settings.HaskellSettingsState$.getHindentPath(HaskellSettingsState.scala:26)
	at intellij.haskell.action.AboutAction.$anonfun$actionPerformed$1(AboutAction.scala:42)
	at intellij.haskell.action.AboutAction.$anonfun$actionPerformed$1$adapted(AboutAction.scala:35)
	at scala.Option.foreach(Option.scala:257)
	at intellij.haskell.action.AboutAction.actionPerformed(AboutAction.scala:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$2(ActionMenuItem.java:315)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:920)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:130)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:295)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:41)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:116)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:126)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

* Highlight external tool names.

* Capitalize each word for the action name.

screenshot

### CODE REVIEW

**Comment by rikvdkleij** [comment]
Thanks for the improvements.

> Originally if I click the About Haskell Project button, it will introduce an NPE: 

No, it's not an NPE. Problem is caused because Java's Object also has `notify` method :smiley: That one is called in case of no project. Very confusing that IntelliJ's API has the same method name.

**Comment by rikvdkleij** [comment]
It seems that you did not push all your changes. I see `html` code in About page :smile:

**Comment by zjhmale** [comment]
I did, the html code is for highlighting 😄 
>It seems that you did not push all your changes. I see html code in About page 😄

**Comment by rikvdkleij** [comment]
I mean literal html code :smile:

**Comment by zjhmale** [comment]
Sorry, I don't understand but I believe the tool names are already in bold 😄 

image

**Comment by rikvdkleij** [comment]
This is what I see:
image

**Comment by zjhmale** [comment]
Ok, I will remove the HTML tags then, seems to be a system sensitive issue 😅

**Pull request merged**
