### PR TITLE
Add config file watcher to restart stack repls

### LINKED ISSUE #134: Config file listener
Show `Restart Stack REPLs` popup immediately after config files (stack.yaml, project.cabal, config.cabal) are changed.

Discussed at #130.

### PR DESCRIPTION
**Pull request by zjhmale**
Fixes #134.

screenshot

### CODE REVIEW

**Comment by rikvdkleij** [comment]
When stack.yaml file is changed, restarting repls is not enough. The restart repls action is not same action as opening project. Opening project also (re)builds tool and rebuilds Hoogle database.

Take a look to logic in RestartStackReplsAction and StackProjectStartupManager.

**Comment by rikvdkleij** [comment]
Also changing resolver in stack.yaml is much bigger change than for example, changing dependencies in cabal file.

I'm considering to only support changes in cabal file for restart repls. That means only rebuild hoogle database has to be added to RestartStackReplsAction.

**Comment by rikvdkleij** [comment]
Btw, also notice that downloading library source files is only done when creating IntelliJ project.

**Comment by zjhmale** [comment]
Yes, `moduleCreated` will only be called once when creating an IntelliJ project https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/module/HaskellModuleBuilder.scala#L48. So maybe we should re-download library source files after cabal file is changed because users may update the dependencies.
>Btw, also notice that downloading library source files is only done when creating IntelliJ project.

**Comment by zjhmale** [comment]
Do you mean changing resolver in stack.yaml will introduce some imcompatible issues?
>Also changing resolver in stack.yaml is much bigger change than for example, changing dependencies in cabal file.

**Comment by rikvdkleij** [comment]
> Do you mean changing resolver in stack.yaml will introduce some imcompatible issues?

I mean, when resolver is changed, project and all tools have to be rebuild.

**Comment by zjhmale** [comment]
@rikvdkleij So how about just stop REPLs and then call this part https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/external/component/StackProjectStartupManager.scala#L39-L87 everytime we want to restart Stack REPLs when config files are updated or project SDK is changed?

**Comment by rikvdkleij** [comment]
Okay, but I think it's not necessay when project SDK is changed.

**Comment by zjhmale** [comment]
@rikvdkleij There is no need to rebuild tools when project SDK is changed?

**Comment by rikvdkleij** [comment]
> @rikvdkleij There is no need to rebuild tools when project SDK is changed?

Yes, my first thought was not but maybe it's safe to do rebuild if also Project SDK is changed. It depends of course what is changed in Stack binary.

Okay, also do rebuild if Project SDK is changed.

**Comment by zjhmale** [comment]
poke @rikvdkleij

**Comment by zjhmale** [comment]
Two questions may be related to this PR, why we should sleep the thread manually for a second here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L59, to wait for the cleanup process finish? And why we should start globalRepl again here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L69, why restart globalRepl can release memory?

**Comment by zjhmale** [comment]
Oh, I just got an error message like `timeout while executing stack clean`, is that because I did not sleep the thread manually like this https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L59?

**Comment by rikvdkleij** [comment]
> Oh, I just got an error message like timeout while executing stack clean, is that because I did not sleep the thread manually like this https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L59?

No, it's because default timeout of StackCommandLine is too short. You can pass timeout to override default timeout.

**Comment by rikvdkleij** [comment]
> Why we should sleep the thread manually for a second here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L59, to wait for the cleanup process finish?

Just some pause to give repls time to stop.

**Comment by rikvdkleij** [comment]
> Why we should start globalRepl again here https://github.com/rikvdkleij/intellij-haskell/blob/master/src/main/scala/intellij/haskell/action/RestartStackReplsAction.scala#L69, why restart globalRepl can release memory?

That is to release memory usage of global repl. When preloading cache with globel repl it takes a lot of memory.

**Comment by zjhmale** [comment]
Thanks! I think I got the answers 😄

**Comment by zjhmale** [comment]
@rikvdkleij So should I also add a manual pause after exit REPLs here https://github.com/zjhmale/intellij-haskell/blob/b38e47ad8cb0daac5231cd81514332f27a0c2abe/src/main/scala/intellij/haskell/external/component/StackProjectStartupManager.scala#L53?

**Comment by rikvdkleij** [comment]
> @rikvdkleij So should I also add a manual pause after exit REPLs here https://github.com/zjhmale/intellij-haskell/blob/b38e47ad8cb0daac5231cd81514332f27a0c2abe/src/main/scala/intellij/haskell/external/component/StackProjectStartupManager.scala#L53 ?

Yes, but you can test if it works without manual pause. It's just some precaution.

**Comment by zjhmale** [comment]
Ok, it all works fine without the manual pause at the moment, but it is safer to add it up I believe 😄 
>Yes, but you can test if it works without manual pause. It's just some precaution.

**Comment by zjhmale** [comment]
poke @rikvdkleij

**Comment by zjhmale** [comment]
poke @rikvdkleij

**Comment by rikvdkleij** [comment]
After changing cabal file or Stack SDK the Stack repls restart does not check if another restart/build is already in process.

**Comment by rikvdkleij** [comment]
And thanks for your PR! :smile:

**Comment by rikvdkleij** [comment]
Also, it would be nice in both cases if you can ignore restart of repls.

**Comment by rikvdkleij** [comment]
It looks like stack is changing the yaml file after build because I keep getting the `Config file is updated` notification even when I not change the file. I can not ignore it.....

**Pull request merged**
