### PR TITLE
Add screenshot to README.

### PR DESCRIPTION
**Pull request by epost**

### CODE REVIEW

**Comment by rikvdkleij** [comment]
@epost It's not (yet) possible to compile Haskell files from within IntelliJ, so maybe the message in status bar is misleading?

**Comment by epost** [comment]
Hm, is that message customisable from within the plugin? If not, I think it's somewhat unfortunate, but I wouldn't necessarily hold back on the screenshots because of it. A caveat might suffice?

**Comment by rikvdkleij** [comment]
It looks like you compiled a project in another IntelliJ window.

**Comment by epost** [comment]
Ok, I'll close this one then.

**Pull request closed without merging**
