### PR TITLE
Reformat using hindent after apply hlint quickfix

### PR DESCRIPTION
**Pull request by zjhmale**
Related to #151.

It is better to automatically trigger hindent formatting after applying hlint quick fix 😃

### CODE REVIEW

**Comment by rikvdkleij** [comment]
I do not think it is a good idea to always format the whole after applying suggestion. I was considering to use hindent only on the expression. Hindent can not always parse part of expresion

**Comment by zjhmale** [comment]
Oh, yeah, good idea, I will do that 😄

**Comment by zjhmale** [comment]
@rikvdkleij will only reformat with hindent for the commonParent expression now 😄

**Comment by rikvdkleij** [comment]
Did you test this well? Because I have experience with `hindent` that it can only handle complete expressions. There is no guarantee that `commonParent`is a complete expression.

You can better use `HaskellPsiUtil.findExpressionParent`

**Comment by zjhmale** [comment]
Thanks Rik, I noticed the problem and test this change in some cases, but yeah, using `findExpressionParent` is much more safer 😄 
>Did you test this well? Because I have experience with hindent that it can only handle complete expressions. There is no guarantee that commonParentis a complete expression.
You can better use HaskellPsiUtil.findExpressionParent

**Comment by rikvdkleij** [comment]
Thanks!

**Pull request merged**
